steps:
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vue-multiagent-frontend:latest', './frontend']
  
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vue-multiagent-backend:latest', './backend']
  
  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vue-multiagent-frontend:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vue-multiagent-backend:latest']
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vue-multiagent-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vue-multiagent-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=35.193.26.19,DB_USER=root,DB_PASS=,DB_NAME=multiagent_db,FRONTEND_URL=https://vue-multiagent-frontend-j6nsgbqxwq-uc.a.run.app'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,SECRET_KEY=jwt-secret-key:latest'
      - '--timeout'
      - '300'
      - '--memory'
      - '512Mi'
  
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vue-multiagent-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vue-multiagent-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/vue-multiagent-frontend:latest'
  - 'gcr.io/$PROJECT_ID/vue-multiagent-backend:latest'